version: "1"
services:
  connect:
    hostname: kafkaconnect
    image: "kafka-connect-extended-image-2"
    ports:
      - '29092:9092'
      - '28083:8083'
      - '22181:2181'
      - '23306:3306'
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "192.168.202.248:9092"
      CONNECT_REST_PORT: "8083"
      CONNECT_GROUP_ID: "quickstart"
      CONNECT_CONFIG_STORAGE_TOPIC: "config" 
      CONNECT_OFFSET_STORAGE_TOPIC: "offsets" 
      CONNECT_STATUS_STORAGE_TOPIC: "status" 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1" 
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1" 
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1" 
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter" 
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafkaconnecthost" 
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    


